sonar.projectKey=sabarishwaran261082-SCE_Autonomous-DevSecOps-Framework
sonar.organization=sabarishwaran261082-sce

# Project information
sonar.projectName=Autonomous-DevSecOps-Framework
sonar.projectVersion=1.0

# Source code
sonar.sources=app

# Exclude unnecessary files
sonar.exclusions=**/__pycache__/**,**/.pytest_cache/**,**/uploads/**

# Python version
sonar.python.version=3.11

# Encoding
sonar.sourceEncoding=UTF-8